"""
Seed data for initial database population.

This module implements the Factory Pattern to generate consistent,
extensible initial data. Data is defined separately from schema
for better maintainability and follows OCP (Open/Closed Principle).

Allows easy extension: add new sports/plateaux without modifying
the application code, just extend PLATEAUX_DATA.
"""

from app.domain.models import Plateau


def build_plateaux_series(type_sport: str, emplacement: str, capacite: int, count: int) -> list[dict]:
    """Generate M-series plateaux for a sport and zone (M1..Mn)."""
    return [
        {
            "nom": f"{type_sport} - {emplacement} - M{index}",
            "type_sport": type_sport,
            "capacite": capacite,
            "emplacement": emplacement,
        }
        for index in range(1, count + 1)
    ]


# Define all initial plateaux data
# Extension-friendly: add new entries without touching application logic
PLATEAUX_DATA = [
    *build_plateaux_series("Gymnase", "Zone Nord", 20, 5),
    *build_plateaux_series("Gymnase", "Zone Sud", 20, 5),
    *build_plateaux_series("Piscine", "Zone Est - Olympique", 30, 3),
    *build_plateaux_series("Piscine", "Zone Est - Semi-olympique", 30, 3),
    *build_plateaux_series("Soccer", "Zone Ouest", 22, 5),
    *build_plateaux_series("Tennis", "Zone A", 4, 3),
    *build_plateaux_series("Tennis", "Zone B", 4, 3),
    *build_plateaux_series("Volleyball", "Zone Centre", 12, 3),
]


def create_plateau_from_data(data: dict) -> Plateau:
    """
    Factory method to create a Plateau domain object from seed data.
    
    Args:
        data: Dictionary with keys: nom, type_sport, capacite, emplacement
        
    Returns:
        Plateau: Domain object ready for persistence
    """
    return Plateau(
        id=None,  # Auto-generated by database
        nom=data["nom"],
        type_sport=data["type_sport"],
        capacite=data["capacite"],
        emplacement=data["emplacement"],
    )
