"""
Seed data for initial database population.

This module implements the Factory Pattern to generate consistent,
extensible initial data. Data is defined separately from schema
for better maintainability and follows OCP (Open/Closed Principle).

Allows easy extension: add new sports/plateaux without modifying
the application code, just extend PLATEAUX_DATA.
"""

from app.domain.models import Plateau


# Define all initial plateaux data
# Extension-friendly: add new entries without touching application logic
PLATEAUX_DATA = [
    # Tennis courts
    {
        "nom": "Tennis - Zone A",
        "type_sport": "Tennis",
        "capacite": 4,
        "emplacement": "Zone A",
    },
    {
        "nom": "Tennis - Zone B",
        "type_sport": "Tennis",
        "capacite": 4,
        "emplacement": "Zone B",
    },
    # Gymnases
    {
        "nom": "Gymnase M1",
        "type_sport": "Gymnase",
        "capacite": 20,
        "emplacement": "Zone Nord",
    },
    {
        "nom": "Gymnase M2",
        "type_sport": "Gymnase",
        "capacite": 20,
        "emplacement": "Zone Nord",
    },
    {
        "nom": "Gymnase M3",
        "type_sport": "Gymnase",
        "capacite": 20,
        "emplacement": "Zone Sud",
    },
    # Swimming pool
    {
        "nom": "Piscine",
        "type_sport": "Piscine",
        "capacite": 30,
        "emplacement": "Zone Est",
    },
    # Soccer field
    {
        "nom": "Terrain Soccer",
        "type_sport": "Soccer",
        "capacite": 22,
        "emplacement": "Zone Ouest",
    },
    # Volleyball court
    {
        "nom": "Terrain Volleyball",
        "type_sport": "Volleyball",
        "capacite": 12,
        "emplacement": "Zone Centre",
    },
]


def create_plateau_from_data(data: dict) -> Plateau:
    """
    Factory method to create a Plateau domain object from seed data.
    
    Args:
        data: Dictionary with keys: nom, type_sport, capacite, emplacement
        
    Returns:
        Plateau: Domain object ready for persistence
    """
    return Plateau(
        id=None,  # Auto-generated by database
        nom=data["nom"],
        type_sport=data["type_sport"],
        capacite=data["capacite"],
        emplacement=data["emplacement"],
    )
