{{- if .Values.api.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.api.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.api.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end }}
