{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
  {{- if .Values.api.enabled }}
  - host: {{ .Values.api.ingress.hosts[0].host }}
    http:
      paths:
      {{- range .Values.api.ingress.hosts[0].paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ .Values.api.name }}
            port:
              number: {{ .Values.api.service.port }}
      {{- end }}
  {{- end }}
  {{- if .Values.frontend.enabled }}
  - host: {{ .Values.frontend.ingress.hosts[0].host }}
    http:
      paths:
      {{- range .Values.frontend.ingress.hosts[0].paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ .Values.frontend.name }}
            port:
              number: {{ .Values.frontend.service.port }}
      {{- end }}
  {{- end }}
  {{- if or .Values.api.ingress.tls .Values.frontend.ingress.tls }}
  tls:
  {{- if .Values.api.ingress.tls }}
  {{- range .Values.api.ingress.tls }}
  - secretName: {{ .secretName }}
    hosts:
    {{- range .hosts }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- end }}
  {{- if .Values.frontend.ingress.tls }}
  {{- range .Values.frontend.ingress.tls }}
  - secretName: {{ .secretName }}
    hosts:
    {{- range .hosts }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
