name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::671765845629:role/github-actions-role
          aws-region: us-east-1
      
      - name: Upload to S3
        run: |
          aws s3 sync . s3://systeme-de-reservation-plateaux-sportifs \
            --exclude ".git/*" \
            --exclude ".venv/*" \
            --exclude ".pytest_cache/*" \
            --exclude "__pycache__/*" \
            --exclude ".coverage" \
            --exclude ".coveragerc" \
            --exclude "*.pyc" \
            --delete
